### ISSUE TITLE
Add User-Dispatchable Config Testing Workflow

### ISSUE THREAD

**Issue by CodeGat** [ACCESS-NRI/access-om3-configs#119]
In a similar vein to https://github.com/ACCESS-NRI/access-om2-configs/blob/main/.github/workflows/generate-initial-checksums.yml, collaborate with @anton-seaice to create a similar user-dispatchable workflow for checksum creation. 

Some initial questions (which may require a slight reworking of `ACCESS-NRI/model-config-tests` CI):
* Tagging of checksums isn't required, so if we don't use tags, what do we compare checksums against?

**Comment by anton-seaice** [comment]
I think in a PR, compare against the checksum in the branch being merged into.

For a user-triggered workflow, maybe the user has to specify the branch with the checksum to compare to?

Although, typically, a branch named 

`feat-025_jra55do_ryf-iss191` could be compared to `dev-025_jra55do_ryf`

Anyway - I think I don't understand the question ... in generating initial checksums there is nothing to compare against ... ?

**Comment by CodeGat** [comment]
Ah correct, initial checksums wouldn't have to compare to anything :D I was thinking about the future case for PRs

**Comment by CodeGat** [comment]
Closed via https://github.com/ACCESS-NRI/access-om3-configs/pull/121
